spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/capstonedesign_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: capstonedesign_user
    password: Hhs2684021@!@
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: dd5d9a7dca19656b14ea717de8480978
            client-secret: knAjWM27IzgBlk2LQ4W9gWwKX9ib2UPz
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kako.com/v2/user/me
            user-name-attribute: id