jwt:
  secret: hello.world.ee.ff
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/capstonedesign_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: capstonedesign_user
    password: Hhs2684021@!@
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 956078510095-udsnstgimq57c81p5mqbf97gakgdh7hj.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace